### ISSUE TITLE
uledge generates a empty report.thml with the example example.ledger

### ISSUE THREAD

**Issue by gmt4** [danpat/uledger#1]
For first-starters I'd be nice to get a non-empty web report

```
$ git clone https://github.com/danpat/uledger.git
$ cd uledger
$ ./uledger.py -f example.ledger web
$ lynx -dump report.html

$ # Check that the produced report.html is empty.
```

The cause is that the the interval of years computed at web.make_report() is empty `[]`.
I've attached a quick patch to address the issue.

```
Date: Thu, 5 Nov 2015 15:05:30 +0100
Subject: [PATCH] uledger: Fix web.py make_report date interval [startyear, endyear[

---
 web.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/web.py b/web.py
index a5322a3..b20e85f 100644
--- a/web.py
+++ b/web.py
@@ -38,7 +38,7 @@ def make_report(ledger,destdir):
     enddate = ledger.enddate()

     startyear = startdate.split("-")[0]
-    endyear = enddate.split("-")[0]
+    endyear = str(int(enddate.split("-")[0])+1)

     # Year by year

-- 
2.1.4
```

Next thing to figure now is why the report.html now correctly handles the years,
but no accounting data is provided in the report :)

**Comment by danpat** [comment]
Ah, thanks for that fix.

`uledger.py` itself assumes no specific structure, but the web report does.  It needs the following:

```
Orgname:Assets
Orgname:Expenses
Orgname:Income
Orgname:Liabilities
Orgname:Equity
Orgname2:Assets
Orgname2:Expenses
Orgname2:Income
Orgname2:Liabilities
Orgname2:Equity
```

I have a couple of side businesses, as well as "Personal" accounts all mixed into the same ledger files.

I'm not quite sure what the best approach here is.  The report works best when it knows which accounts are assets/income/equity/expenses/liabilities, and it's hard-coded to look for those names right now.  Maybe I could add support for an extension to:

http://www.ledger-cli.org/3.0/doc/ledger3.html#Keeping-it-Consistent

and do something like:

```
accountgroup Personal
account Personal:Assets  type Assets
```
